baseurl = "https://romantic-feynman-d9b44e.netlify.com/"
disqusShortname = "spf13"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-type-theme"
title = "Type theme"
[params]
author = "Eu mesmo"
avatar = "img/avatar.png"
copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"
description = "Add a description of your website"
gravatar = "your@email.com"
headerImage = ""
headerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."
keywords = ""
[params.social]
behance = ""
bitbucket = ""
dribbble = ""
email = "hello@example.com"
facebook = ""
flickr = ""
github = "digitalcraftsman/hugo-type-theme"
gitlab = ""
googleplus = ""
homepage = true
instagram = ""
linkedin = ""
pinterest = ""
reddit = ""
rss = true
soundcloud = ""
stackexchange = ""
steam = ""
trello = ""
tumblr = ""
twitter = ""
wordpress = ""
youtube = ""
